// 01_Number
console.log("01_Number")
console.log(typeof  2);
console.log(typeof 5.14);
console.log(typeof -127)
// _Domingo-D'noite 27/9/2026
console.log("----------")
console.log("02_Operações Aritméticas: ")
console.log("Soma(2 + 4):", 2 + 4)
console.log("Subtração(10 - 5):", 10 - 5)
console.log("Multpicação(2 * 4):", 2 * 4)
console.log("Divisão(10 - 5):", 10 / 5)
console.log("----------")
console.log("03_Special Numbers")
console.log(typeof Infinity)
console.log(typeof infinity)
console.log(12 * "alk");
console.log(typeof NaN)
console.log("----------")
console.log("04_Strings")
console.log("um texto")
console.log(`Mais um texto`)
console.log(`753`)
console.log(typeof "um texto")
console.log( typeof `Mais um texto`)
console.log("---------")
// 05_simbolos especias
console.log(" 05_simbolos especias")
console.log("Testando a \n quebra de linha ")
console.log("Espaçamento \t de tab")
 console.log("---------")
// 06_Concatenação
console.log(" 06_Concatenação")
console.log("Oi," + "tudo" + " bem ?")
console.log(`Testando` + `  como `+ `crase!!`);
 console.log("---------")
// 07_Interpolação(Template Strings)
console.log(" 07_Interpolação(Template Strings)")
console.log(`A soma de 2 + 2 é: ${2 + 2 } `)
console.log(`Podemos executar qualquer coisa aqui ${console.log("Teste")}`)
// terça-feira_d'noite, 29/09/2026
 console.log("---------")
console.log("08_Boolean")
console.log(true)
console.log("5 é Maior que 20 :", 5 > 20)
console.log("30 é Maior que 10 :", 30 > 10)
console.log(typeof true)
 console.log("---------")
console.log("09_Comparações ")
console.log(5 <=  5)
console.log(5 < 5)
console.log(10 == 10 )
console.log(9 == 9)
console.log(10 == 9)
 console.log("---------")
console.log("10_Idêntico ")
// Quarta-feira_D'noite,30/09/2026
console.log(9 =="9")
console.log(9 + "9")
console.log(9 === "9")
console.log(9 != "9")
console.log(9 !== "9")
 console.log("---------")
console.log("11_Operadores Logicos ")
console.log( true && true)
console.log(false && true)
console.log(5 > 2 && 2 < 10)
console.log(5 > 2 && "André Luis" === 3)
console.log(5 > 2 || "André Luis" === 3)
console.log(5 < 2 || 5 > 100)
console.log(!true)
console.log(5 > 2)
console.log(!5 > 2)