// 14 salva na memoria
// Domingo_D'madrugada,04/10/2026;
// 1 - variavel
let nome = "André Luis";
console.log(nome)
nome = "André Luis Kunert";
console.log("Olá meu",nome,"estudante de programação");
const idade = 44; 
console.log("Eu tenho ", idade,"anos")
console.log(typeof nome)
console.log(typeof idade)
// Segunda-feira_D'Noite
// let 2teste = "Invalido"
// let @teste = "invalido"
let a = 10,
    b  = 20,
    c = 30;
    console.log(a, b, c)
// 
const nomeCompleto =  "Matheus Battisti"
const nomeCompleto1 =  "André Luis Kunert"
console.log(nomeCompleto)
console.log(nomeCompleto1)
let _teste = "OK"
let $teste = "ok"
console.log(_teste, $teste)
// // 3 - prompt
// const age = prompt("Informe sua idade:")
// console.log(` Você tem ${age} anos`)
// 4 alert
// alert("Erro no sistema")
// alert("É Numero 10")
// Quarta-feira_D'Noite,07/10/2026
// 5_Math
console.log(Math.max(5, 3, 1, 2, 7, 4, 6))
console.log(Math.floor(5.14))
console.log(Math.ceil(5.15))
// 6_console
console.log("Teste;;;?")
console.error("I am sorry my Friend ")
console.warn("AVISO")
// Padding com width
//  7_If
const m = 10;
if(m > 5){
 console.log("M é Maior que 5")
}
const user = "André Luis"
if (user === "André Luis") {
    console.log(`Ola ${user}`)
}
if (user === "Maria") {
    console.log("Olá Maria")
    
}
console.log(user === "André Luis", user === "Maria")
// 8_else
const loggedIn = false
if(loggedIn){
    console.log("Está autenticado...")
} else{
     console.log("Não está autenticado...")
}
// 
const q = 10;
const w = 15;
if(q > 5 && w > 20){
  console.log("Números mais altos")
} else{
    console.log("Os numeros não mais altos ")
}
//