// 14 salva na memoria
// Domingo_D'madrugada,04/10/2026;
// 1 - variavel
let nome = "André Luis";
console.log(nome)
nome = "André Luis Kunert";
console.log("Olá meu",nome,"estudante de programação");
const idade = 44; 
console.log("Eu tenho ", idade,"anos")
console.log(typeof nome)
console.log(typeof idade)
// Segunda-feira_D'Noite
// let 2teste = "Invalido"
// let @teste = "invalido"
let a = 10,
    b  = 20,
    c = 30;
    console.log(a, b, c)
// 
const nomeCompleto =  "Matheus Battisti"
const nomeCompleto1 =  "André Luis Kunert"
console.log(nomeCompleto)
console.log(nomeCompleto1)
let _teste = "OK"
let $teste = "ok"
console.log(_teste, $teste)
// // 3 - prompt
// const age = prompt("Informe sua idade:")
// console.log(` Você tem ${age} anos`)
// 4 alert
alert("Erro no sistema")
alert("É Numero 10")

